In [1]:
import pandas as pd
import itertools
import matplotlib.pyplot as plt

import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer #Count Vector Space Model
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn import metrics #Matrix Builder
from sklearn.model_selection import KFold #Import KFold
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score,multilabel_confusion_matrix
from scipy.sparse import csr_matrix

from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding, Dropout

from keras import Sequential
from keras.models import load_model

from sklearn.model_selection import KFold

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

_`, skiprows=[i for i in range(1, 1000) ]`_

In [2]:
df = pd.read_csv('D:\kuliah\THE ONLY TA THINGS\DATA\data clean\cleaned_15000_data_sample.csv')
df.head()

content  score   
0                                              Keren      5  \
1  Woy tiktok menangis gw event mlbb creator base...      5   
2  Halo disini saya ingin menyampaikan kepada and...      4   
3  Jangan mau main tiktokla paket kuota cpt hbis ...      2   
4                    Sangat menghibur asyik dan seru      5   

                    at  label   
0  2023-04-14 19:21:43      1  \
1  2023-04-07 23:01:39      1   
2  2023-04-07 20:13:21      1   
3  2023-04-11 17:06:47     -1   
4  2023-04-13 21:08:45      1   

                                           cleansing   
0                                              Keren  \
1  Woy tiktok menangis gw event mlbb creator base...   
2  Halo disini saya ingin menyampaikan kepada and...   
3  Jangan mau main tiktokla paket kuota cpt hbis ...   
4                    Sangat menghibur asyik dan seru   

                                        case_folding   
0                                              keren  \
1  woy tiktok menangis gw event mlbb creator base...   
2  halo disini saya ingin menyampaikan kepada and...   
3  jangan mau main tiktokla paket kuota cpt hbis ...   
4                    sangat menghibur asyik dan seru   

                                         no_unwanted   
0                                              keren  \
1  woy tiktok menangis gw event mlbb creator base...   
2  halo disini saya ingin menyampaikan kepada and...   
3  jangan mau main tiktokla paket kuota cpt hbis ...   
4                    sangat menghibur asyik dan seru   

                                            tokenize   
0                                          ['keren']  \
1  ['woy', 'tiktok', 'menangis', 'gw', 'event', '...   
2  ['halo', 'disini', 'saya', 'ingin', 'menyampai...   
3  ['jangan', 'mau', 'main', 'tiktokla', 'paket',...   
4    ['sangat', 'menghibur', 'asyik', 'dan', 'seru']   

                                       normalization   
0                                          ['keren']  \
1  ['oi', 'tiktok', 'menangis', 'gue', 'event', '...   
2  ['halo', 'di sini', 'saya', 'ingin', 'menyampa...   
3  ['jangan', 'mau', 'main', 'tiktokla', 'paket',...   
4    ['sangat', 'menghibur', 'asyik', 'dan', 'seru']   

                                           stopwords   
0                                          ['keren']  \
1  ['tiktok', 'menangis', 'gue', 'event', 'mlbb',...   
2  ['di sini', 'membuka', 'komen', 'lag', 'koneks...   
3  ['main', 'tiktokla', 'paket', 'kuota', 'cepat'...   
4                              ['menghibur', 'seru']   

                                            stemming   
0                                          ['keren']  \
1  ['tiktok', 'menang', 'gue', 'event', 'mlbb', '...   
2  ['di sini', 'buka', 'komen', 'lag', 'koneksi',...   
3  ['main', 'tiktokla', 'paket', 'kuota', 'cepat'...   
4                                  ['hibur', 'seru']   

                                               clean  
0                                              keren  
1  tiktok menang gue event mlbb creator base gue ...  
2  di sini buka komen lag koneksi internet bagus ...  
3  main tiktokla paket kuota cepat habis potong k...  
4                                         hibur seru

In [3]:
df['label'].value_counts()

label
 1    6315
-1    1169
 0     354
Name: count, dtype: int64

In [6]:
# Split the data into features and labels
df['review_clean'] = df['clean'].astype(str)
reviews = df['review_clean'].values

labels = pd.get_dummies(df['label']).values.astype(int)


# convert labels to one-hot encoding
# labels = tf.keras.utils.to_categorical(df['label'], num_classes=3)

In [7]:
labels

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       ...,
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1]])

In [8]:
# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(reviews,labels, test_size=0.3, random_state=42)

In [9]:
# define tf-idf vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=1000)
train_tfidf_features = tfidf_vectorizer.fit_transform(x_train).toarray()
test_tfidf_features = tfidf_vectorizer.transform(x_test).toarray()

In [10]:
max_length = max([len(i) for i in reviews])
# max_length = 3
# Pad sequences to have equal length
X_train_padded = pad_sequences(train_tfidf_features, maxlen=max_length, padding='post', truncating='post')
X_test_padded = pad_sequences(test_tfidf_features, maxlen=max_length, padding='post', truncating='post')


In [11]:
print("X_train padded shape: ", X_train_padded.shape)
print("X_test padded shape: ", X_test_padded.shape)
print("y_train shape: ", y_train.shape)
print("y_test shape: ", y_test.shape)

X_train padded shape:  (5486, 523)
X_test padded shape:  (2352, 523)
y_train shape:  (5486, 3)
y_test shape:  (2352, 3)


### tfidf lalu split

In [ ]:
# define tf-idf vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=10000)
tfidf_features = tfidf_vectorizer.fit_transform(reviews).toarray()

In [ ]:
# define tokenizer
tokenizer = Tokenizer(num_words=10000, oov_token="<OOV>")
tokenizer.fit_on_texts(reviews)
sequences = tokenizer.texts_to_sequences(reviews)



# pad sequence
padded_sequences = pad_sequences(sequences, maxlen=50, padding='post', truncating='post')

In [ ]:
# combine sequence and tf-idf features
combined_features = tf.concat([tf.cast(tf.constant(tfidf_features), tf.float32), tf.cast(tf.constant(padded_sequences),  tf.float32)], axis=1)

In [ ]:
# Pad the sequences
max_length = max([len(i) for i in combined_features])
combined_features_in_max_length = tf.keras.preprocessing.sequence.pad_sequences(combined_features, maxlen=max_length, padding='post')

In [ ]:
# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(combined_features_in_max_length, labels, test_size=0.3, random_state=42)

## Define RNN model

In [12]:
class RNNModel(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, lstm_units, num_classes, dropout_rate=0.2):
        super(RNNModel, self).__init__()
        self.embedding_layer = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        # self.bi_lstm_layer = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(lstm_units))
        self.lstm = tf.keras.layers.LSTM(lstm_units, dropout=dropout_rate, recurrent_dropout=dropout_rate)
        self.dense_layer = tf.keras.layers.Dense(num_classes, activation='softmax')
        # self.output_layer = tf.keras.layers.Dense(num_classes, activation='sigmoid')

    def call(self, inputs):
        x = self.embedding_layer(inputs)
        x = self.lstm(x)
        # x = self.bi_lstm_layer(x)
        x = self.dense_layer(x)
        # output = self.output_layer(x)
        return x

### uji coba k-fold

In [13]:

# split data into K folds
kf = KFold(n_splits=3, random_state=0, shuffle = True)

# # shuffle the data
# indices = np.arange(len(combined_features))
# np.random.shuffle(indices)
# combined_features_data = combined_features[indices]
# labels = labels[indices]

#### kfold dengan split di luar loop

In [14]:
# Loop through each fold
for fold, (train_idx, val_idx) in enumerate(kf.split(X_train_padded, y_train)):
    
    # Split train data into train and validation sets
    x_train_fold = X_train_padded[train_idx]
    y_train_fold = y_train[train_idx]
    x_val_fold = X_train_padded[val_idx]
    y_val_fold = y_train[val_idx]

    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)


    # build and compile the model
    model = RNNModel(vocab_size=10000, embedding_dim=32, lstm_units=64, num_classes=3)
    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

    # train the model
    history = model.fit(x_train_fold, y_train_fold, epochs=5, batch_size=32, validation_data=(x_val_fold, y_val_fold))

    # evaluate the model on test set
    score = model.evaluate(X_test_padded, y_test, batch_size=32, verbose=1)
    print("Fold %d: %s: %.2f%%" % (fold+1, model.metrics_names[1], score[1]*100))   

Epoch 1/5
115/115 [==============================] - 91s 750ms/step - loss: 0.6448 - accuracy: 0.8023 - val_loss: 0.6053 - val_accuracy: 0.8054
Epoch 2/5
115/115 [==============================] - 75s 654ms/step - loss: 0.5974 - accuracy: 0.8083 - val_loss: 0.6021 - val_accuracy: 0.8054
Epoch 3/5
115/115 [==============================] - 80s 692ms/step - loss: 0.5965 - accuracy: 0.8083 - val_loss: 0.6021 - val_accuracy: 0.8054
Epoch 4/5
115/115 [==============================] - 76s 661ms/step - loss: 0.6005 - accuracy: 0.8083 - val_loss: 0.6003 - val_accuracy: 0.8054
Epoch 5/5
74/74 [==============================] - 7s 97ms/step - loss: 0.6029 - accuracy: 0.8019
Fold 1: accuracy: 80.19%
Epoch 1/5
115/115 [==============================] - 79s 655ms/step - loss: 0.6497 - accuracy: 0.7979 - val_loss: 0.5795 - val_accuracy: 0.8168
Epoch 2/5
115/115 [==============================] - 71s 615ms/step - loss: 0.6133 - accuracy: 0.8026 - val_loss: 0.5777 - val_accuracy: 0.8168
Epoch 3/5
115

In [15]:
# Predict the labels for the testing data
label_pred_prob = model.predict(X_test_padded)
label_pred = label_pred_prob.argmax(axis=1)
label_test_one_dim = np.argmax(y_test, axis=1)


print(confusion_matrix(label_test_one_dim, label_pred))
print(classification_report(label_test_one_dim, label_pred))
print("Precision: ",precision_score(label_test_one_dim, label_pred, average="macro"))
print("Recall: ",recall_score(label_test_one_dim, label_pred, average="macro"))
print("F1: ",f1_score(label_test_one_dim, label_pred,  average="macro"))
print("Accuracy: ",accuracy_score(label_test_one_dim, label_pred))

74/74 [==============================] - 7s 92ms/step
[[   0    0  368]
 [   0    0   98]
 [   0    0 1886]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       368
           1       0.00      0.00      0.00        98
           2       0.80      1.00      0.89      1886

    accuracy                           0.80      2352
   macro avg       0.27      0.33      0.30      2352
weighted avg       0.64      0.80      0.71      2352

Precision:  0.2672902494331066
Recall:  0.3333333333333333
F1:  0.29668082428818626
Accuracy:  0.8018707482993197


c:\Users\Madluke\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Madluke\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Madluke\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [ ]:
label_pred


In [ ]:
set(label_pred)

In [ ]:
label_test_one_dim

In [ ]:
label_pred_prob

In [ ]:
label_value = pd.DataFrame(label_test_one_dim)
label_value.value_counts()

In [ ]:
print("x_train: ", x_train.shape)
print("x_test: ", x_test.shape)
print("y_train: ", y_train.shape)
print("y_test: ", y_test.shape)

#### kfold dengan split di dalam loop

In [ ]:
# iterate over each fold
for fold, (train_index, test_index) in enumerate(kf.split(tfidf_features)):
  print("fold: ", fold+1)
  # split data into train and test set
  x_train, x_test = tfidf_features[train_index], tfidf_features[test_index]
  y_train, y_test = labels[train_index], labels[test_index]

  # build and compile the model
  model = RNNModel(vocab_size=10000, embedding_dim=32, lstm_units=64, num_classes=3)
  model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


  # train the model
  history = model.fit(tfidf_features, labels, epochs=5, batch_size=32)

  # evaluate the model on test set
  score = model.evaluate(x_test, y_test, batch_size=32, verbose=1)
  print("Fold %d: %s: %.2f%%" % (fold, model.metrics_names[1], score[1]*100))

### uji coba 1

In [ ]:
model = RNNModel(vocab_size=5000, embedding_dim=32, lstm_units=64, num_classes=3)

In [ ]:
# compile model

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [ ]:
# train model
model.fit(X_train_vec, y_train, epochs=10, batch_size=32, validation_data=(X_test_vec, y_test))

In [ ]:
# Predict the labels for the testing data
label_pred_prob = model.predict(test_tfidf_features)
label_pred = label_pred_prob.argmax(axis=1)-1
label_test_one_dim = np.argmax(y_test, axis=1)-1


# # Hitung confusion matrix untuk setiap label
# cm = multilabel_confusion_matrix(y_test, y_pred)

# print("Confusion matrix untuk label 1:")
# print(cm[0])

# print(confusion_matrix(y_test, y_pred))
print(classification_report(label_test_one_dim, label_pred))
print("Precision: ",precision_score(label_test_one_dim, label_pred, average="macro"))
print("Recall: ",recall_score(label_test_one_dim, label_pred, average="macro"))
print("F1: ",f1_score(label_test_one_dim, label_pred,  average="macro"))
print("Accuracy: ",accuracy_score(label_test_one_dim, label_pred))

In [ ]:
label_pred

In [ ]:
label_value = pd.DataFrame(label_test_one_dim)
label_value.value_counts()